TEXTS = {
    'uz': {
        # Ro'yxatdan o'tish
        'start': "Salom! Botdan foydalanish uchun tilni tanlang:",
        'register': "Ro'yxatdan o'tish uchun Ism-sharifingizni kiriting:",
        'phone': "Telefon raqamingizni yuboring (pastdagi tugmani bosing):",
        'card_req': "Karta raqamingizni kiriting (16 xonali):",
        'card_error': "Karta raqami xato (Luhn algoritmi yoki uzunlik). Qayta urinib ko'ring:",
        'success': "Muvaffaqiyatli ro'yxatdan o'tdingiz, ",
        'db_error': "Tizimda xatolik! Ma'lumotlarni saqlash imkoni bo'lmadi.",
        'contact_btn': "📞 Kontaktni yuborish",
        'card_safety': "\n(Karta raqamingiz xavfsizlik uchun o'chirildi)",
        'not_registered': "⚠️ Avval ro'yxatdan o'ting: /start",

        # Karta va Menyu
        'my_cards_title': "💳 <b>Sizning kartalaringiz:</b>\n\n",
        'card_balance': "💰 Balans: <code>{balance:,}</code> UZS\n",
        'card_status': "🟢 Status: {status}\n",
        'no_cards': "❌ Sizda hali karta ulanmagan.",
        'insufficient_funds': "⚠️ Mablag' yetarli emas!",
        'trans_success': "{icon} <b>Karta operatsiyasi</b>\n━━━━━━━━━━━━━━━\n💰 Summa: <b>{prefix}{amount:,} UZS</b>\n📅 Sana: {date}\n💳 Balans: <b>{balance:,} UZS</b>\n━━━━━━━━━━━━━━━\n✅ Muvaffaqiyatli.",
        
        # Tarix va Yordam
        'history_title': "📜 <b>Oxirgi operatsiyalar (..{last4}):</b>\n\n",
        'history_empty': "📭 Tranzaksiyalar tarixi bo'sh.",
        'help_text': (
            "❓ <b>Yordam bo'limi:</b>\n\n"
            "🔹 /start - Ishga tushirish\n"
            "🔹 /my_cards - Mening kartalarim\n"
            "🔹 /history - Tranzaksiyalar tarixi\n"
            "🔹 /transfer - Pul o'tkazish (P2P)\n"
            "🔹 /settings - Sozlamalar (Til)\n\n"
            "Savollaringiz bo'lsa admin bilan bog'laning."
        ),
        'admin_btn': "👨‍💻 Admin bilan bog'lanish",
        'trans_in': 'tushum',
        'trans_out': 'yechildi',

        # P2P Transfer
        'transfer_req': "💸 Pul o'tkazish uchun qabul qiluvchi karta raqamini kiriting:",
        'transfer_amount': "💰 O'tkazma summasini kiriting:",
        'transfer_self': "❌ O'z kartangizga pul o'tkaza olmaysiz!",
        'card_not_found': "❌ Qabul qiluvchi karta tizimda topilmadi!",
        'receiver_found': "👤 Qabul qiluvchi: <b>{name}</b>",
        'transfer_success_sender': "💸 <b>Pul o'tkazildi!</b>\n━━━━━━━━━━━━━━━\n👤 Kimga: <b>{to}</b>\n💰 Summa: -{amount:,} UZS\n💳 Balans: {balance:,} UZS",
        'transfer_success_receiver': "💰 <b>Pul kelib tushdi!</b>\n━━━━━━━━━━━━━━━\n👤 Kimdan: <b>{from_user}</b>\n💰 Summa: +{amount:,} UZS\n💳 Balans: {balance:,} UZS",

        # Sozlamalar
        'settings_menu': "⚙️ <b>Sozlamalar bo'limi</b>\n\nTanlang:",
        'change_lang_btn': "🌐 Tilni o'zgartirish",
        'lang_changed': "✅ Til muvaffaqiyatli o'zgartirildi!",

        # Admin Panel
        'admin_panel': "👨‍💻 <b>Admin panel</b>\n\nAmallardan birini tanlang:",
        'adm_btn_stats': "📊 Statistika",
        'adm_btn_send': "📢 Xabar yuborish",
        'adm_btn_pay': "💰 Balansni boshqarish",
        'adm_pay_req': "Foydalanuvchi Chat ID sini kiriting:",
        'adm_amount_req': "Summani kiriting (masalan: 50000 yoki -20000):",
        'adm_pay_success': "✅ Foydalanuvchi balansi muvaffaqiyatli o'zgartirildi!",
        'stats_text': "📊 <b>Bot statistikasi:</b>\n\n👤 Foydalanuvchilar: {u} ta\n💳 Kartalar: {c} ta\n🔄 Tranzaksiyalar: {t} ta",
        'broadcast_req': "📢 Barcha foydalanuvchilarga yuboriladigan xabarni yuboring:",
        'broadcast_start': "⏳ Xabar yuborish boshlandi (Jami: {total})...",
        'broadcast_done': "✅ Yakunlandi! {count} ta foydalanuvchiga yetib bordi."
    },
    'ru': {
        'start': "Привет! Выберите язык:",
        'register': "Введите ФИО:",
        'phone': "Отправьте номер:",
        'card_req': "Введите номер карты:",
        'card_error': "Ошибка!",
        'success': "Вы успешно зарегистрировались, ",
        'db_error': "Ошибка!",
        'contact_btn': "📞 Отправить контакт",
        'card_safety': "\n(Номер карты удален)",
        'not_registered': "⚠️ Зарегистрируйтесь: /start",
        'my_cards_title': "💳 <b>Ваши карты:</b>\n\n",
        'card_balance': "💰 Баланс: <code>{balance:,}</code> UZS\n",
        'card_status': "🟢 Статус: {status}\n",
        'no_cards': "❌ Нет карт.",
        'insufficient_funds': "⚠️ Недостаточно средств!",
        'trans_success': "{icon} <b>Операция</b>\n━━━━━━━━━━━━━━━\n💰 Сумма: <b>{prefix}{amount:,} UZS</b>\n📅 Дата: {date}\n💳 Баланс: <b>{balance:,} UZS</b>\n━━━━━━━━━━━━━━━\n✅ Успешно.",
        'history_title': "📜 <b>История (..{last4}):</b>\n\n",
        'history_empty': "📭 История пуста.",
        'help_text': "❓ <b>Помощь:</b>\n\n🔹 /start - Запуск\n🔹 /my_cards - Карты\n🔹 /history - История\n🔹 /transfer - Перевод\n🔹 /settings - Настройки",
        'admin_btn': "👨‍💻 Связаться с админом",
        'trans_in': 'пополнение',
        'trans_out': 'списание',
        'transfer_req': "💸 Введите номер карты получателя:",
        'transfer_amount': "💰 Введите сумму:",
        'transfer_self': "❌ Нельзя самому себе!",
        'card_not_found': "❌ Карта не найдена!",
        'receiver_found': "👤 Получатель: <b>{name}</b>",
        'transfer_success_sender': "💸 <b>Перевод выполнен!</b>\n━━━━━━━━━━━━━━━\n👤 Кому: <b>{to}</b>\n💰 Сумма: -{amount:,} UZS\n💳 Баланс: {balance:,} UZS",
        'transfer_success_receiver': "💰 <b>Получен перевод!</b>\n━━━━━━━━━━━━━━━\n👤 От: <b>{from_user}</b>\n💰 Сумма: +{amount:,} UZS\n💳 Баланс: {balance:,} UZS",
        'settings_menu': "⚙️ <b>Раздел настроек</b>",
        'change_lang_btn': "🌐 Изменить язык",
        'lang_changed': "✅ Язык изменен!",
        'admin_panel': "👨‍💻 <b>Админ панель</b>",
        'adm_btn_stats': "📊 Статистика",
        'adm_btn_send': "📢 Рассылка",
        'adm_btn_pay': "💰 Управление балансом",
        'adm_pay_req': "Введите Chat ID:",
        'adm_amount_req': "Введите сумму:",
        'adm_pay_success': "✅ Баланс изменен!",
        'stats_text': "📊 <b>Статистика:</b>\n👤 Юзеров: {u}\n💳 Карт: {c}\n🔄 Транзакций: {t}",
        'broadcast_req': "📢 Отправьте сообщение:",
        'broadcast_start': "⏳ Начато ({total})...",
        'broadcast_done': "✅ Готово! Получили: {count}"
    },
    'en': {
        'start': "Hello! Choose a language:",
        'register': "Enter your full name:",
        'phone': "Send your phone number:",
        'card_req': "Enter your card number:",
        'card_error': "Card number error. Try again:",
        'success': "Successfully registered, ",
        'db_error': "System error!",
        'contact_btn': "📞 Send Contact",
        'card_safety': "\n(Card number deleted)",
        'not_registered': "⚠️ Register first: /start",
        'my_cards_title': "💳 <b>Your cards:</b>\n\n",
        'card_balance': "💰 Balance: <code>{balance:,}</code> UZS\n",
        'card_status': "🟢 Status: {status}\n",
        'no_cards': "❌ No cards attached.",
        'insufficient_funds': "⚠️ Insufficient funds!",
        'trans_success': "{icon} <b>Transaction</b>\n━━━━━━━━━━━━━━━\n💰 Amount: <b>{prefix}{amount:,} UZS</b>\n📅 Date: {date}\n💳 Balance: <b>{balance:,} UZS</b>\n━━━━━━━━━━━━━━━\n✅ Successful.",
        'history_title': "📜 <b>Recent history (..{last4}):</b>\n\n",
        'history_empty': "📭 History is empty.",
        'help_text': "❓ <b>Help:</b>\n\n🔹 /start - Start\n🔹 /my_cards - My cards\n🔹 /history - History\n🔹 /transfer - Transfer\n🔹 /settings - Settings",
        'admin_btn': "👨‍💻 Contact Admin",
        'trans_in': 'income',
        'trans_out': 'outcome',
        'transfer_req': "💸 Enter receiver card number:",
        'transfer_amount': "💰 Enter amount:",
        'transfer_self': "❌ You cannot transfer to yourself!",
        'card_not_found': "❌ Card not found!",
        'receiver_found': "👤 Receiver: <b>{name}</b>",
        'transfer_success_sender': "💸 <b>Money sent!</b>\n━━━━━━━━━━━━━━━\n👤 To: <b>{to}</b>\n💰 Amount: -{amount:,} UZS\n💳 Balance: {balance:,} UZS",
        'transfer_success_receiver': "💰 <b>Money received!</b>\n━━━━━━━━━━━━━━━\n👤 From: <b>{from_user}</b>\n💰 Amount: +{amount:,} UZS\n💳 Balance: {balance:,} UZS",
        'settings_menu': "⚙️ <b>Settings Menu</b>",
        'change_lang_btn': "🌐 Change Language",
        'lang_changed': "✅ Language changed!",
        'admin_panel': "👨‍💻 <b>Admin panel</b>",
        'adm_btn_stats': "📊 Stats",
        'adm_btn_send': "📢 Broadcast",
        'adm_btn_pay': "💰 Manage Balance",
        'adm_pay_req': "Enter Chat ID:",
        'adm_amount_req': "Enter amount:",
        'adm_pay_success': "✅ Balance updated!",
        'stats_text': "📊 <b>Stats:</b>\n👤 Users: {u}\n💳 Cards: {c}\n🔄 Transactions: {t}",
        'broadcast_req': "📢 Send message:",
        'broadcast_start': "⏳ Started ({total})...",
        'broadcast_done': "✅ Done! Reached: {count}"
    }
}
